spring:
  profiles:
    active: dev
  application:
    name: csse-api
  security:
    # Google Login
    oauth2:
      client:
        registration:
          google:
            client-id: 9935716285-dk8j19o1a90tffh468312temlsai6c68.apps.googleusercontent.com
            client-secret: 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


logging:
  level:
    org:
      springframework:
        security: TRACE


