spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-sysdba.alwaysdata.net:5432/sysdba_cssedb
    username: sysdba
    password: hackers-squad
    hikari:
      maximum-pool-size: 4
  devtools:
    restart:
      enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    cors:
      allowed-origins:
        - http://localhost:5173
      allowed-methods:
        - GET
        - POST
        - PATCH
        - PUT
        - DELETE
        - OPTIONS
      allow-credentials: true
